package com.iminit.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings({"serial", "unchecked"})
public abstract class BaseWordSentence<M extends BaseWordSentence<M>> extends Model<M> implements IBean {

	public M setId(java.lang.Integer id) {
		set("id", id);
		return (M)this;
	}

	public java.lang.Integer getId() {
		return getInt("id");
	}

	public M setWordIds(java.lang.String wordIds) {
		set("wordIds", wordIds);
		return (M)this;
	}

	public java.lang.String getWordIds() {
		return getStr("wordIds");
	}

	public M setContent(java.lang.String content) {
		set("content", content);
		return (M)this;
	}

	public java.lang.String getContent() {
		return getStr("content");
	}

	public M setCategory(java.lang.String category) {
		set("category", category);
		return (M)this;
	}

	public java.lang.String getCategory() {
		return getStr("category");
	}

	public M setUser(java.lang.String user) {
		set("user", user);
		return (M)this;
	}

	public java.lang.String getUser() {
		return getStr("user");
	}

	public M setCreateTime(java.util.Date createTime) {
		set("create_time", createTime);
		return (M)this;
	}

	public java.util.Date getCreateTime() {
		return get("create_time");
	}

	public M setUpdateTime(java.util.Date updateTime) {
		set("update_time", updateTime);
		return (M)this;
	}

	public java.util.Date getUpdateTime() {
		return get("update_time");
	}

}
