package com.iminit.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("blog", "id", Blog.class);
		arp.addMapping("file", "id", File.class);
		arp.addMapping("memo", "id", Memo.class);
		arp.addMapping("user", "id", User.class);
		arp.addMapping("word", "id", Word.class);
		arp.addMapping("word_sentence", "id", WordSentence.class);
	}
}

