package com.iminit.common.model;

import com.iminit.common.model.base.BaseMemo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Memo extends BaseMemo<Memo> {
	public static final Memo dao = new Memo().dao();
}
