package com.iminit.common.model;

import com.iminit.common.model.base.BaseNum;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Num extends BaseNum<Num> {
	public static final Num dao = new Num().dao();
}
