package com.iminit.common.model;

import com.iminit.common.model.base.BaseWord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Word extends BaseWord<Word> {
	public static final Word dao = new Word().dao();
}
