package com.iminit.common.model;

import com.iminit.common.model.base.BaseWordSentence;
import com.jfinal.plugin.activerecord.Db;
import com.jfinal.plugin.activerecord.Record;

import java.util.List;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class WordSentence extends BaseWordSentence<WordSentence> {
	public static final WordSentence dao = new WordSentence().dao();

	public List<Record> wordsSentenceList(String wordIds) {
		List<Record> records = Db.find("SELECT * FROM word_sentence WHERE wordIds LIKE CONCAT(?,'%')", wordIds);
		return records;
	}
}
